return {
  -- "yetone/avante.nvim",
  -- event = "VeryLazy",
  -- lazy = false,
  -- version = "*",
  -- opts = {
  --   provider = "ollama",
  --   vendors = {
  --     ollama = {
  --       __inherited_from = "openai",
  --       api_key_name = "",
  --       endpoint = "http://127.0.0.1:11434/v1",
  --       model = "deepseek-r1:7b",
  --     },
  --   },
  -- },
  -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false",
  -- dependencies = {
  --   "stevearc/dressing.nvim",
  --   "nvim-lua/plenary.nvim",
  --   "MunifTanjim/nui.nvim",
  --   "hrsh7th/nvim-cmp", -- autocompletion for avante commands and mentions
  --   {
  --     -- support for image pasting
  --     "HakonHarnes/img-clip.nvim",
  --     event = "VeryLazy",
  --     opts = {
  --       -- recommended settings
  --       default = {
  --         embed_image_as_base64 = false,
  --         prompt_for_file_name = false,
  --         drag_and_drop = {
  --           insert_mode = true,
  --         },
  --         -- required for Windows users
  --         use_absolute_path = true,
  --       },
  --     },
  --   },
  -- },
}
